tango_with_django_project/rango/urls.py
from django.conf.urls import re_path

from rango import views

app_name = 'rango'
urlpatterns = [
    re_path(r'^$', views.index, name='index'),
    re_path(r'^about/$', views.about, name='about'),
    re_path(r'^category/add/$', views.add_category, name='add_category'),
    re_path(r'^category/(?P<category_name_slug>[\w\-]+)/$', views.show_category, name='show_category'),
    re_path(r'^category/(?P<category_name_slug>[\w\-]+)/add/$', views.add_page, name='add_page'),
]

tango_with_django_project/tango_with_django_project/urls.py
from django.contrib import admin
from django.urls import path, re_path
from django.conf.urls import include

from rango import views

urlpatterns = [
    path('', views.index, name='index'),
    re_path(r'^rango/', include('rango.urls')),
    path('admin/', admin.site.urls),
]

tango_with_django_project/rango/models.py
from django.db import models
from django.template.defaultfilters import slugify


class Category(models.Model):
    name = models.CharField(max_length=128, unique=True)
    views = models.IntegerField(default=0)
    likes = models.IntegerField(default=0)
    slug = models.SlugField(unique=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super().save(*args, **kwargs)

    class Meta:
        verbose_name_plural = 'categories'
    
    def __str__(self):
        return self.name


class Page(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    title = models.CharField(max_length=128)
    url = models.URLField()
    views = models.IntegerField(default=0)

    def __str__(self):
        return self.title

tango_with_django_project/rango/forms.py
from django import forms
from rango.models import Page, Category


class CategoryForm(forms.ModelForm):
    name = forms.CharField(max_length=128, help_text="Please enter the category name.")
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    likes = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    slug = forms.CharField(widget=forms.HiddenInput(), required=False)

    class Meta:
        model = Category
        fields = ('name',)


class PageForm(forms.ModelForm):
    title = forms.CharField(max_length=128, help_text="Please enter the title of the page.")
    url = forms.URLField(max_length=200, help_text="Please enter the URL of the page.")
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)

    class Meta:
        model = Page
        exclude = ('category',)

    def clean(self):
        cleaned_data = self.cleaned_data
        url = cleaned_data.get('url')

        if url and not url.startswith('http://'):
            url = 'http://' + url
            cleaned_data['url'] = url
        return cleaned_data

tango_with_django_project/rango/views.py
from django.http import HttpResponse
from django.shortcuts import render
from rango.models import Category
from rango.models import Page
from rango.forms import CategoryForm, PageForm

def index(request):
    category_list = Category.objects.order_by('-likes')[:5]
    page_list = Page.objects.order_by('-views')[:5]
    context = {'categories': category_list, 'pages': page_list}
    return render(request, 'rango/index.html', context=context)

def show_category(request, category_name_slug):
    context = {}
    try:
        category = Category.objects.get(slug=category_name_slug)
        pages = Page.objects.filter(category=category)
        context['pages'] = pages
        context['category'] = category
    except Category.DoesNotExist:
        context['pages'] = None
        context['category'] = None
    return render(request, 'rango/category.html', context)

def about(request):
    context = {}
    return render(request, 'rango/about.html', context=context)

def add_category(request):
    form = CategoryForm()

    if request.method == 'POST':
        form = CategoryForm(request.POST)
        if form.is_valid():
            form.save(commit=True) # F() to avoid race conditions
            return index(request)
        else:
            print(form.errors)
    return render(request, 'rango/add_category.html', {'form': form})

def add_page(request, category_name_slug):
    try:
        category = Category.objects.get(slug=category_name_slug)
    except:
        category = None

    form = PageForm()
    if request.method == 'POST':
        form = PageForm(request.POST)
        if form.is_valid():
            if category:
                page = form.save(commit=False)
                page.category = category
                page.views = 0
                page.save()
                return show_category(request, category_name_slug)
        else:
            print(form.errors)
    context = {'form': form, 'category': category}
    return render(request, 'rango/add_page.html', context)

tango_with_django_project/templates/rango/about.html
<!DOCTYPE>
{% load staticfiles %}
<html>
    <head>
        <title>Rango</title>
    </head>
    <body>
        <h1>About</h1>
        <a href="/rango/">Index</a>
        <br/>
        <img src="{% static 'images/image.png' %}" alt="Some image"/>
        <p>This tutorial has been put together by ninja</p>
    </body>
</html>

tango_with_django_project/templates/rango/add_category.html
<!DOCTYPE html>
<html>
    <head>
        <title>Rango</title>
    </head>
    <bod>
        <h1>Add a category</h1>
        <div>
            <form id="category_form" method="POST" action="{% url 'rango:add_category' %}">
                {% csrf_token %}
                {% for hidden in form.hidden_fields %}
                    {{ hidden }}
                {% endfor %}
                {% for field in form.visible_fields %}
                    {{ field.errors }}
                    {{ field.help_text }}
                    {{ field }}
                {% endfor %}
                <input type="submit" name="submit" value="Create Category" />
            </form>
        </div>
    </bod>
</html>

tango_with_django_project/templates/rango/add_page.html
<!DOCTYPE html>
<html>
    <head>
        <title>Rango</title>
    </head>
    <bod>
        <div>
            {% if category %}
            <h1>{{ category.name }}</h1>
            {% endif %}
            <h2>Add a page</h2>
        </div>
        <div>
            <form id="page_form" method="POST" action="{% url 'rango:add_page' category.slug %}">
                {% csrf_token %}
                {% for hidden in form.hidden_fields %}
                    {{ hidden }}
                {% endfor %}
                {% for field in form.visible_fields %}
                    {{ field.errors }}
                    {{ field.help_text }}
                    {{ field }}
                {% endfor %}
                <input type="submit" name="submit" value="Add page" />
            </form>
        </div>
    </bod>
</html>

tango_with_django_project/templates/rango/base.html
<!DOCTYPE html>
{% load staticfiles %}
{% load rango_template_tags %}
<html>
    <head lang="en">
        <meta charset="UTF-8">
        <title>{% block title_block %}Rango{% endblock %}</title>
    </head>
    <body>
        <div>
            {% block body_block %}
            <h1>Hello</h1>
            {% endblock %}
        </div>
        <div>
            {% block sidebar_block %}
                {% get_category_list %}
            {% endblock %}
        </div>
        <hr/>
        <div>
            <ul>
                <li>
                    <a href="{% url 'rango:add_category' %}">Add a new category</a>
                </li>
                <li>
                    <a href="{% url 'rango:about' %}">About</a>
                </li>
                <li>
                    <a href="{% url 'rango:index' %}">Index</a>
                </li>
            </ul>
        </div>
    </body>
</html>

tango_with_django_project/templates/rango/category.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
Rango
{% endblock %}

{% block body_block %}
    {% if category %}
        <h1>{{ category.name }}</h1>
        <a href="{% url 'rango:add_page' category.slug %}">Add a page</a>
        {% if pages %}
            <ul>
                {% for page in pages %}
                    <li><a href="{{ page.url }}">{{ page.title }}</a></li>
                {% endfor %}
            </ul>
        {% else %}
            <strong>No pages currently in category.</strong>
        {% endif %}
    {% else %}
        <p>The specified category does not exist.</p>
    {% endif %}
{% endblock %}

tango_with_django_project/templates/rango/cats.html
<ul>
    {% if cats %}
        {% for c in cats %}
            <li>
                <a href="{% url 'rango:show_category' c.slug %}">{{ c.name }}</a>
            </li>
        {% endfor %}
    {% else %}
        <li>
            <strong>There are no categories present.</strong>
        </li>
    {% endif %}
</ul>

tango_with_django_project/templates/rango/index.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
    <head>
        <title>Rango</title>
    </head>
    <body>
        <h1>Rango says...</h1>
        <p>hey there partner!</p>
        <div>
            {% if categories %}
                <h2>Most liked categories</h2>
                <ul>
                    {% for category in categories %}
                        <li>
                            <a href="{% url 'rango:show_category' category.slug %}">{{ category.name }}</a>
                        </li>
                    {% endfor %}
                </ul>
            {% else %}
                <strong>There are no categories present.</strong>
            {% endif %}
            <a href="{% url 'rango:add_category' %}">Add a new category</a>
        </div>
        <div>
            {% if pages %}
                <h2>Most viewed pages</h2>
                <ul>
                    {% for page in pages %}
                        <li>
                            <a href="{{ page.url }}">{{ page.title }}</a>
                        </li>
                    {% endfor %}
                </ul>
            {% endif %}
        </div>
        <div>
            <a href="/rango/about/">About</a>
            <br/>
            <img src="{% static 'images/image.png' %}" alt="Some image"/>
        </div>
    </body>
</html>